# Generated by Django 5.2.10 on 2026-01-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('timeframe', models.CharField(default='1m', max_length=10)),
                ('min_vol_1m', models.PositiveIntegerField(default=50000)),
                ('rvol_lookback_minutes', models.PositiveIntegerField(default=30)),
                ('rvol_1m_threshold', models.FloatField(default=4.0)),
                ('rvol_5m_threshold', models.FloatField(default=2.5)),
                ('min_pct_change_1m', models.FloatField(default=0.8)),
                ('min_pct_change_5m', models.FloatField(default=2.0)),
                ('require_green_candle', models.BooleanField(default=False)),
                ('require_hod_break', models.BooleanField(default=False)),
                ('cooldown_minutes', models.PositiveIntegerField(default=15)),
                ('realert_on_new_hod', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScannerTriggerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('triggered_at', models.DateTimeField(db_index=True)),
                ('reason_tags', models.JSONField(default=list)),
                ('o', models.FloatField(blank=True, null=True)),
                ('h', models.FloatField(blank=True, null=True)),
                ('l', models.FloatField(blank=True, null=True)),
                ('c', models.FloatField(blank=True, null=True)),
                ('v', models.FloatField(blank=True, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('vol_1m', models.FloatField(blank=True, null=True)),
                ('vol_5m', models.FloatField(blank=True, null=True)),
                ('avg_vol_1m_lookback', models.FloatField(blank=True, null=True)),
                ('rvol_1m', models.FloatField(blank=True, null=True)),
                ('rvol_5m', models.FloatField(blank=True, null=True)),
                ('pct_change_1m', models.FloatField(blank=True, null=True)),
                ('pct_change_5m', models.FloatField(blank=True, null=True)),
                ('hod', models.FloatField(blank=True, null=True)),
                ('broke_hod', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerUniverseTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='UserScannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
