# Generated by Django 5.0.14 on 2026-01-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscannersettings',
            name='cleared_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
