# Generated by Django 5.0.14 on 2026-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_userscannersettings_cleared_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscannersettings',
            name='pushover_device',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userscannersettings',
            name='pushover_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userscannersettings',
            name='pushover_priority',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscannersettings',
            name='pushover_sound',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userscannersettings',
            name='pushover_user_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
