# Generated by Django 5.0.14 on 2026-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_userscannersettings_pushover_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscannersettings',
            name='notify_min_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userscannersettings',
            name='notify_only_hod_break',
            field=models.BooleanField(default=False),
        ),
    ]
