# Generated by Django 5.0.14 on 2026-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_userscannersettings_notify_min_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscannersettings',
            name='live_feed_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
