# Generated by Django 5.0.14 on 2026-01-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_userscannersettings_live_feed_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerconfig',
            name='rvol_lookback_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
    ]
