# Generated by Django 5.2.6 on 2025-09-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('day_start_equity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('day_end_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('max_trades', models.PositiveIntegerField(default=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StrategyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quantity', models.IntegerField()),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('risk_per_share', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('comment', models.TextField(blank=True)),
                ('journal_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='journal.journalday')),
                ('strategy_tags', models.ManyToManyField(blank=True, to='journal.strategytag')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal_attachments/')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='journal.trade')),
            ],
        ),
    ]
