# Generated by Django 5.2.7 on 2025-10-05 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_start_equity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('day_end_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('entry_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('journal_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='journal.journalday')),
                ('strategy_tags', models.ManyToManyField(blank=True, related_name='trades', to='journal.strategytag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal_attachments/')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='journal.trade')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('dark_mode', models.BooleanField(default=False)),
                ('max_risk_per_trade_pct', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('max_trades_per_day', models.PositiveIntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
