# Generated by Django 5.2.7 on 2025-10-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
