# Generated by Django 5.2.7 on 2025-10-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_usersettings_entry_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategytag',
            options={'ordering': ['name']},
        ),
    ]
