# Generated by Django 5.2.7 on 2025-10-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_strategytag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
