# Generated by Django 5.2.7 on 2025-10-12 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_trade_exit_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('FEE', 'Fee'), ('CORRECTION', 'Correction')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('at_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='journal.journalday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-at_time', '-id'),
            },
        ),
    ]
