# Generated by Django 5.2.7 on 2025-11-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_accountadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='entry_emotion',
            field=models.CharField(blank=True, choices=[('NEUTRAL', 'Neutral'), ('BIASED', 'Biased')], default='NEUTRAL', max_length=16),
        ),
        migrations.AddField(
            model_name='trade',
            name='entry_emotion_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_emotion',
            field=models.CharField(blank=True, choices=[('NEUTRAL', 'Neutral'), ('BIASED', 'Biased')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_emotion_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
