# Generated by Django 5.2.8 on 2025-11-20 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_trade_entry_emotion_trade_entry_emotion_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'status', 'exit_time'], name='journal_tra_user_id_f05502_idx'),
        ),
    ]
