# Generated by Django 5.2.9 on 2025-12-31 20:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_trade_journal_tra_user_id_f05502_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='commission_entry',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trade',
            name='commission_exit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='commission_mode',
            field=models.CharField(choices=[('PCT', 'Percentage'), ('FIXED', 'Fixed amount')], default='FIXED', max_length=8),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='commission_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
