# Generated by Django 5.2.9 on 2026-01-01 17:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_trade_commission_entry_trade_commission_exit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='commission_cap_pct_of_notional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='commission_min_per_side',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='commission_per_share',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='commission_mode',
            field=models.CharField(choices=[('PCT', 'Percentage'), ('FIXED', 'Fixed amount'), ('PER_SHARE', 'Per share (IBKR fixed-style)')], default='FIXED', max_length=16),
        ),
    ]
