# Generated by Django 5.2.9 on 2026-01-03 18:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_usersettings_commission_cap_pct_of_notional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='journal.trade')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
                'indexes': [models.Index(fields=['trade', 'timestamp'], name='journal_tra_trade_i_a205ec_idx')],
            },
        ),
    ]
