# Generated by Django 5.2.9 on 2026-01-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_tradefill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='fill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='journal.tradefill'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['trade', 'uploaded_at'], name='journal_att_trade_i_09f94a_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['fill', 'uploaded_at'], name='journal_att_fill_id_61a224_idx'),
        ),
    ]
