# Generated by Django 5.2.9 on 2026-01-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_attachment_options_attachment_fill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attachment',
            name='journal_att_trade_i_09f94a_idx',
        ),
        migrations.RemoveIndex(
            model_name='attachment',
            name='journal_att_fill_id_61a224_idx',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='fill',
        ),
    ]
